### PR TITLE
Feat 7 grids

### PR DESCRIPTION
**Pull request by SinchanaMS**
Created grid layouts.
- grids-2: 1:1 and 70:30 ratios
- grids-3

image

image

image

### CODE REVIEW

**Review by zoef-yt — APPROVED** [review]
Good to merge.

**Comment by dev-ashishsethi** [comment]
Grids looks good but it would be great if you add CTA color to buttons

**Comment by aiman-ansari** [comment]
Agreed with Ashish it will look good if you add color

**Comment by SinchanaMS** [comment]
Made the PR Changed. Merging to dev.

**Pull request merged**
